name = "PaperMod"
license = "MIT"
licenselink = "https://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
homepage = "https://github.com/adityatelange/hugo-PaperMod"
description = "Minimal included PaperMod theme placeholder to allow Hugo build."
